n = input('digita ai:')
print('O tipo primitivo da palava({}) é {}'.format(n, type(n)))
print('{} é alfanumerio? {}'.format(n, n.isalnum()))
print('{} contem só letras? {}'.format(n, n.isalpha()))
print('{} contem só numeros? {}'.format(n, n.isnumeric()))
print('{} contem só letras maiusculas? {}'.format(n, n.isupper()))
print('{} contem só letras minusculas? {}'.format(n, n.islower()))
print('{} contem só espaços? {}'.format(n, n.isspace()))
print('{} contem só numeros? {}'.format(n, n.isdecimal()))
